FROM ubuntu:22.04

MAINTAINER DANIL <89242489714@mail.ru>

RUN apt-get update
RUN apt-get install -y pycharm community
#apt-get clean

COPY HelloWorld.py /home/tamik/tutorial

ENTRYPOINT ["HelloWorld"]


